spring.application.name=messaging-app

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

messagingApp.uploads.location=${user.dir}/files

spring.servlet.multipart.location=private/tomtemp
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.liquibase.enabled=true
spring.liquibase.change-log=/db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:h2:mem:testdb
spring.liquibase.user=sa
spring.liquibase.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.liquibase.driver-class-name=org.h2.Driver